# Generated by Django 6.0.5 on 2026-05-30 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketattachment_ticketnote_noteattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='elaboration_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
